export const TOP_100_COMMANDS = [
  // ── AUTHENTICATION ──────────────────────────────────────────────
  { command: 'help', description: 'Show all available command clusters' },
  { command: 'auth', description: 'Session login: /auth PWD' },
  { command: 'logout', description: 'Kill current administrative session' },

  // ── CASE MANAGEMENT ──────────────────────────────────────────────
  { command: 'queue', description: 'Show active cases' },
  { command: 'recent', description: 'List N recent cases: /recent 5' },
  { command: 'oldest', description: 'Identify oldest unresolved case' },
  { command: 'filter', description: 'Filter tickets by status: /filter Resolved' },
  { command: 'status', description: 'Check status of specific ID: /status ID' },
  { command: 'id', description: 'Lookup full ticket details by ID' },
  { command: 'trace', description: 'Trace message path and metadata' },
  { command: 'forensics', description: 'Run IP and UA forensics on case' },
  { command: 'export', description: 'Generate JSON export of case data' },
  { command: 'transcript', description: 'Fetch full chat history for a case' },
  { command: 'history', description: 'View all tickets from a specific user' },
  { command: 'reply', description: 'Send response to active case: /reply ID msg' },
  { command: 'whisper', description: 'Send internal admin note: /whisper ID msg' },
  { command: 'note', description: 'Add static note to dossier: /note ID msg' },
  { command: 'resolve', description: 'Mark case as resolved' },
  { command: 'close', description: 'Hard-close case (Archive)' },
  { command: 'reopen', description: 'Restore a resolved/closed case' },
  { command: 'pause', description: 'Temporarily pause case processing' },
  { command: 'unpause', description: 'Resume case processing' },
  { command: 'escalate', description: 'Move case to Tier 2' },
  { command: 'deescalate', description: 'Move case back to Tier 1' },
  { command: 'priority', description: 'Set priority (high/low): /priority ID high' },
  { command: 'retitle', description: 'Change case subject line' },
  { command: 'tag', description: 'Add category label: /tag ID billing' },
  { command: 'assign', description: 'Hand case to agent: /assign ID name' },
  { command: 'ban', description: 'Perma-ban user IP + email' },
  { command: 'quarantine', description: 'Move user to sandboxed state' },
  { command: 'purge', description: 'Wipe all records for a specific case' },
  { command: 'wipe_whispers', description: 'Delete internal notes for a case' },

  // ── INTELLIGENCE ─────────────────────────────────────────────
  { command: 'lookup', description: 'Deep lookup: /lookup TARGET' },
  { command: 'whois', description: 'Fetch dossier for email' },
  { command: 'ipcheck', description: 'Forensics on IP address' },
  { command: 'sentinel', description: 'Active threat scan (IP clusters)' },
  { command: 'threats', description: 'List identified high-risk sectors' },
  { command: 'dupes', description: 'Scan for sockpuppet registrations' },
  { command: 'spamcheck', description: 'Analyze global spam metrics' },
  { command: 'blacklist', description: 'View last 10 entries in ban roster' },
  { command: 'shadowban', description: 'Stealth-ban an IP address' },
  { command: 'unshadow', description: 'Lift stealth-ban from IP' },
  { command: 'unban', description: 'Restore access to user' },

  // ── USER & REGISTRATION ────────────────────────────────────────
  { command: 'registrations', description: 'Daily registration breakdown' },
  { command: 'users', description: 'List N recent users: /users 5' },
  { command: 'waitlist', description: 'Check waitlist metrics' },
  { command: 'approve', description: 'Approve email: /approve EMAIL' },
  { command: 'reject', description: 'Reject email: /reject EMAIL' },
  { command: 'mass_approve', description: 'Approve N users: /mass_approve 10' },
  { command: 'userinfo', description: 'Detailed user profile lookup' },
  { command: 'deleteuser', description: 'Permanently remove user' },
  { command: 'resetotp', description: 'Clear OTP rate limits for user' },

  // ── PLATFORM CONTROL ───────────────────────────────────────────
  { command: 'sys', description: 'Global system health & metrics' },
  { command: 'stats', description: 'Operational throughput report' },
  { command: 'daily', description: 'Review today\'s activity log' },
  { command: 'weekly', description: 'Review this week\'s performance' },
  { command: 'topissues', description: 'Identify most common report types' },
  { command: 'maintenance', description: 'Maintenance mode: /maintenance on/off' },
  { command: 'lock', description: 'Lock public registration' },
  { command: 'unlock', description: 'Unlock public registration' },
  { command: 'emergency', description: 'Declare platform emergency state' },
  { command: 'allclear', description: 'Restore normal operations' },
  { command: 'stealth', description: 'Stealth mode: /stealth on/off' },
  { command: 'banner', description: 'Update site banner message' },
  { command: 'announce', description: 'Send platform announcement' },
  { command: 'alert', description: 'Trigger visual alert on UI' },

  // ── UTILITY & DEVOPS ───────────────────────────────────────────
  { command: 'ping', description: 'Verify server latency' },
  { command: 'uptime', description: 'Check kernel uptime' },
  { command: 'version', description: 'View build version' },
  { command: 'logs', description: 'View latest logs: /logs 10' },
  { command: 'audit', description: 'Fetch latest audit events' },
  { command: 'cleanup', description: 'Purge volatile log tables' },
  { command: 'agentname', description: 'Update your display identity' },
  { command: 'config', description: 'View global configuration' },
  { command: 'setconfig', description: 'Update config: /setconfig K V' },
  { command: 'shrug', description: '¯\\_(ツ)_/¯' }
];
